### ISSUE TITLE
Hi, where is rasterize function?

### ISSUE THREAD

**Issue by mks0601** [ShichenLiu/SoftRas#1]
Hi, thanks for good work!

In soft_renderer/rasterize.py, a function, srf.rasterize, is called. But I cannot figure out where it is defined. Can you give me some help?

**Comment by ShichenLiu** [comment]
Hi,

Thanks for pointing this out. srf.rasterize is a prototype function that we used in previous versions. I just remove that part of the code to make it less confusing. Feeding soft_rasterize with dist_func, aggr_func_rgb and aggr_func_alpha setting to 'hard' is equivalent to standard rasterize function.
