### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by Liusifei** [ShichenLiu/SoftRas#11]
https://github.com/ShichenLiu/SoftRas/blob/d7447be86ad3c8f6d6b22041ed0c550144bf5a9e/soft_renderer/cuda/soft_rasterize_cuda_kernel.cu#L598
atomicAdd(&grad_texture[k], zp_softmax * grad_t);
should be
atomicAdd(&grad_texture[3*j+k], zp_softmax * grad_t);

**Comment by ShichenLiu** [comment]
Hi,

Yes you are right! I have fixed the bug! Thanks for pointing this out!
