### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by goddice** [ShichenLiu/SoftRas#18]
https://github.com/ShichenLiu/SoftRas/blob/a238ad7e3f8326bdcf00096930a4cb0cae1147c0/soft_renderer/functional/look.py#L20

Should be: direction = direction.to(device)

And you might want to process "up" similar as line 15 to 27.

**Comment by lelechen63** [comment]
> https://github.com/ShichenLiu/SoftRas/blob/a238ad7e3f8326bdcf00096930a4cb0cae1147c0/soft_renderer/functional/look.py#L20
> 
> Should be: direction = direction.to(device)
> 
> And you might want to process "up" similar as line 15 to 27.

niubility

**Comment by ShichenLiu** [comment]
Fixed!
