### ISSUE TITLE
Not able to import soft renderer after building

### ISSUE THREAD

**Issue by piyush-bagad** [ShichenLiu/SoftRas#19]
I cloned the git repo and installed as per instructions in `README`.   It ran with some warnings and ended with 
```
Using /home/users/piyushb/anaconda3/envs/anthro/lib/python3.7/site-packages
Finished processing dependencies for soft-renderer==1.0.0
```

Further, on trying to import, it gives the following error message:

```
>>> import soft_renderer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/users/piyushb/projects/SoftRas/soft_renderer/__init__.py", line 1, in <module>
    from . import functional
  File "/home/users/piyushb/projects/SoftRas/soft_renderer/functional/__init__.py", line 4, in <module>
    from .load_obj import load_obj
  File "/home/users/piyushb/projects/SoftRas/soft_renderer/functional/load_obj.py", line 7, in <module>
    import soft_renderer.cuda.load_textures as load_textures_cuda
ModuleNotFoundError: No module named 'soft_renderer.cuda.load_textures'
```

There is no package in the respective directory. Any help?

**Comment by lelechen63** [comment]
I also have the same problem. I am using CUDA 10 with driver 410.79. The pytorch version is 1.2

**Comment by ShichenLiu** [comment]
Hi there,

I think it is related to the path you included it. If you run python in the root dir of Softras, that is not going to work. You might need to import it outside of the folder, or use it as in the example. Thanks.

**Comment by lelechen63** [comment]
> Hi there,
> 
> I think it is related to the path you included it. If you run python in the root dir of Softras, that is not going to work. You might need to import it outside of the folder, or use it as in the example. Thanks.

It works. Thanks.
