### ISSUE TITLE
source.npy shape explanation

### ISSUE THREAD

**Issue by MichalisLazarou** [ShichenLiu/SoftRas#20]
I am trying to understand the dimensions of source.npy represent.(120, 4,64,64). I understand that 120 are the examples and 64*64 are the size of the image, but what is the 4 stand for? I am asking because I am trying to replicate and use SoftRas with another dataset of silhouette images

**Comment by ShichenLiu** [comment]
Hi there,

120 is the dimension of different views and 4 is RGBA channels.
