### ISSUE TITLE
What's the order of this dataset?

### ISSUE THREAD

**Issue by qiao1025566574** [ShichenLiu/SoftRas#27]
Hello, ShichenLiu ! I find there is no hashname in your datasets which are .npz files? Therefore, I want to know how to sort them in order?

**Comment by ShichenLiu** [comment]
Hi,

If you mean the id_to_name map, the number is the ShapeNet category id, you can find it under this [site](https://gist.github.com/tejaskhot/15ae62827d6e43b91a4b0c5c850c168e).

**Comment by qiao1025566574** [comment]
No, I know this id_to_name map. For example, chair category has 6778 models, I see 70% for train, 20% for test  and 10% for val. 

I download Shapenet datasets from [https://www.shapenet.org/](url). But I can't associate this dataset with Shapenet datasets from official website.

Every shapenet model file have a hash name, like '1b84dededd445058e44a5473032f38f' '8ea3fa037107ec737426c116c412c132'. Do you know these .npz file's hashaname?

I sort Shapenet dataset by file name, but these npz file have no law to keep. So I want to know how original author deal this file from official dataset.

Thank you for your reply !!

**Comment by ShichenLiu** [comment]
Oh I see. Then you might be able to find some helpful information [here](https://github.com/xcyan/nips16_PTN/blob/master/prepare_data.sh) :)

**Comment by qiao1025566574** [comment]
Yes！！That‘s I need, thank you！

**Comment by zyz-1998** [comment]
> Yes！！That‘s I need, thank you！
hello,  I would like to ask you a question. When I load data during training, it takes up a lot of my memory. My memory configuration is only 16g. How should I set it to avoid this situation? I look forward to your reply

**Comment by qiao1025566574** [comment]
You can adjust BATCH_SIZE to suitable value instead of read all the dataset once.
It is convenient  that using class DataLoader in pytoch.
