### ISSUE TITLE
Barycentric clipping

### ISSUE THREAD

**Issue by nikhilaravi** [ShichenLiu/SoftRas#30]
Can you explain why you have this clipping step before calculating the z buffer value? 

https://github.com/ShichenLiu/SoftRas/blob/master/soft_renderer/cuda/soft_rasterize_cuda_kernel.cu#L398-L399

**Comment by ShichenLiu** [comment]
Hi,

We clip the z value to avoid it from being too large due to extrapolating triangle depth that are almost perpendicular to the image plane.
