### ISSUE TITLE
How to import camera parameters?

### ISSUE THREAD

**Issue by zyuanbing** [ShichenLiu/SoftRas#39]
Hi,
I want to import a camera parameter file in json format, which include camera eye position, camera focal position, camera up vector, camera focal length, camera skew and principal point, is there any support for importing this?

**Comment by ForrestPi** [comment]
yeah I have  similar question. I want  camera parameters as input tensor . How to realize it ?

**Comment by hao-zhao-1997** [comment]
the same question.

**Comment by ShichenLiu** [comment]
Hi @hzhao1997 , you can use the projection transform module here: https://github.com/ShichenLiu/SoftRas/blob/0beb8aec26e65bac6fe5d41bb2a265f13b616057/soft_renderer/transform.py#L61-L80

P is the extrinsic parameters and orig_size is the image size.
