### ISSUE TITLE
How to calculate L_g in Eq.5?

### ISSUE THREAD

**Issue by mehameha998** [ShichenLiu/SoftRas#4]
Thanks  for your kinedly open source code. But L_g term  in Eq.5 is a little ambiguous. Can you tell me the exact form?

**Comment by ShichenLiu** [comment]
Hi,

The code for computing the loss is [here](https://github.com/ShichenLiu/SoftRas/blob/d96dfb5e557f1a0cf5ee55bc099db725d15b4515/soft_renderer/losses.py#L6)  in the losses.py file!

**Comment by mehameha998** [comment]
Fine. Thanks!

**Comment by mehameha998** [comment]
One more Thing. Could tell me the mean of '*_update' variable (e.g., face_vertices_update in mesh.py)?  It mean face link will update/change ? Thanks! @ShichenLiu
