### ISSUE TITLE
Transformation in deformation

### ISSUE THREAD

**Issue by tejank10** [ShichenLiu/SoftRas#42]
Hello,

I did not understand the meaning behind doing [this](
https://github.com/ShichenLiu/SoftRas/blob/a238ad7e3f8326bdcf00096930a4cb0cae1147c0/examples/demo_deform.py#L39) (line 40 to 45) transformation in the deformation experiment. Could anyone please explain what's going on in it?

**Comment by ShichenLiu** [comment]
Hi there,

We followed the network structure of [NMR](https://github.com/hiroharu-kato/neural_renderer) on this point. I believe the intuition behind is to control the range of vertices within (-1, 1) to prevent highly deformed shapes.
