### ISSUE TITLE
question about backpropagation

### ISSUE THREAD

**Issue by wanghxcis** [ShichenLiu/SoftRas#45]
Thank you for sharing your great work. I'm a little confused about the back propagation process, could you help me? I = sum(wj * cj), in your implementation, it seems that only wj has impact on x, y coordinate, but actually cj also has impact on x, y coordinate either. If my understanding is correct,  what's the meaning of this simplification, or my understanding is wrong? Thanks.

**Comment by ShichenLiu** [comment]
Yes, we indeed considered Cj, check this line:

https://github.com/ShichenLiu/SoftRas/blob/b569bed5759cf2014f9b79c12ad10eef7b80ec34/soft_renderer/cuda/soft_rasterize_cuda_kernel.cu#L615

C_grad_xy includes the gradients from color.
