### ISSUE TITLE
The effect on training speed using softras

### ISSUE THREAD

**Issue by FishWoWater** [ShichenLiu/SoftRas#46]
Hi! Thanks for sharing your nice work! 
I am doing human mesh reconstruction task(with SMPL model). Before I use the mask to supervise our network(i.e. use soft rasterizer), 1 epoch finishes in about 10 mins, but after using softras... It becomes very slow(about 3h a epoch). I don't know whether this is a normal phenomenon.  Does the rasterization generally affect the speed a lot?(In particular, I use 6890 vertices and 13776 faces). Thanks!

**Comment by ShichenLiu** [comment]
I think this is due to too many triangles and also large image size. My solution would be use less triangles / train in a hierarchical way to reduce computation.

**Comment by ssjsusie** [comment]
> Hi! Thanks for sharing your nice work!
> I am doing human mesh reconstruction task(with SMPL model). Before I use the mask to supervise our network(i.e. use soft rasterizer), 1 epoch finishes in about 10 mins, but after using softras... It becomes very slow(about 3h a epoch). I don't know whether this is a normal phenomenon. Does the rasterization generally affect the speed a lot?(In particular, I use 6890 vertices and 13776 faces). Thanks!

Hello, I am also trying the same job. How do you get the non-square rendering result? I see that the SoftRasterizeFunction part makes image_size=256. thank you very much!
