### ISSUE TITLE
How to use this model with custom RGB image?

### ISSUE THREAD

**Issue by t-qureshi** [ShichenLiu/SoftRas#49]
Hi,
Thanks for sharing this amazing work. I am new in this field. I am just curious to evaluate this model by providing any 2D chair image.
I did little try but got an Error,
![image](https://user-images.githubusercontent.com/61450584/80952890-df4b5380-8e13-11ea-857c-df83b36510f4.png)

I don't know how to generate .npz file, if it's compulsory.

**Comment by ShichenLiu** [comment]
It is not compulsory, you can modify the code to directly load rbg images with PIL/skimage.io/cv2. But this npz is formatted as [B, N, C, H, W], if you just want a single image input, you need [1, 1, 3, H, W], where H, W is the image size
