### ISSUE TITLE
ModuleNotFoundError: No module named 'soft_renderer.cuda.load_textures'

### ISSUE THREAD

**Issue by Shilling818** [ShichenLiu/SoftRas#51]
I use Python3.6.5 and Pytorch=1.1.0, and after running "sudo python setup.py install", I found this error.  In "load_obj.py", there is a line "import soft_renderer.cuda.load_textures as load_textures_cuda", but there is just a "load_textures_cuda.cpp" in that folder. Is there any error?

**Comment by hamaadtahir** [comment]
How did you solve this issue?

**Comment by luogyu7** [comment]
Why this  issue is closed ?  Has it been solved ?

**Comment by wrk226** [comment]
You should rename the soft_renderer folder after build the SoftRas, otherwise it will be the same as installed soft_renderer library .  @luogyu7 @hamaadtahir

**Comment by yangyouzi** [comment]
> 构建 SoftRas 后，您应该重命名soft_renderer文件夹，否则它将与soft_renderer库中安装的文件夹相同。@luogyu7@hamaadtahir
Hello, where is the "soft_render library" installed?

**Comment by wrk226** [comment]
> Hello, where is the "soft_render library" installed?

That depends on your environment. For example, in my enviroment, it located in "D:\miniconda3\envs\umr18\Lib\site-packages\soft_renderer-1.0.0-py3.6-win-amd64.egg\soft_renderer".
By the way, this soft_renderer is not the one you need to rename. The folder I mentioned is the one in original code:[soft_renderer](https://github.com/ShichenLiu/SoftRas/tree/master/soft_renderer)
