### ISSUE TITLE
Question about  the sigma value

### ISSUE THREAD

**Issue by lijing1996** [ShichenLiu/SoftRas#52]
Thanks for sharing your nice work!

My question is why the sigma value in test.py is larger than train.py.
In train.py:

> https://github.com/ShichenLiu/SoftRas/blob/f6442793d0b3a4e02e76c2dd3a0209e1ac6c278b/examples/recon/train.py#L36

And it is decayed to be smaller during training. But in test.py:

> https://github.com/ShichenLiu/SoftRas/blob/f6442793d0b3a4e02e76c2dd3a0209e1ac6c278b/examples/recon/test.py#L27

Maybe the sigma value in test.py should be smaller than in train.py.
Thanks.

**Comment by ShichenLiu** [comment]
In fact, the sigma value is useless in the test.py. It is for providing gradients for the inverse rendering process.
