### ISSUE TITLE
Memory consumption during data set loading during training

### ISSUE THREAD

**Issue by zyz-1998** [ShichenLiu/SoftRas#53]
Hello, ShichenLiu ! Thank you for your work. When I load data during training, it takes up a lot of my memory. My memory configuration is only 16g. How should I set it to avoid this kind of situation? I look forward to your reply

**Comment by ShichenLiu** [comment]
You can write your own dataloader: (1) save each image in the huge tensor as separate image files (.png); (2) in the dataloader, read the images on-the-fly in the __getitem__ method
