### ISSUE TITLE
Euclidian distance using barycentric coordinates

### ISSUE THREAD

**Issue by NotAnyMike** [ShichenLiu/SoftRas#55]
Hi there,

I don't understand fully these lines (basically the definition of `a0` and `t0`) starting from this line https://github.com/ShichenLiu/SoftRas/blob/f6442793d0b3a4e02e76c2dd3a0209e1ac6c278b/soft_renderer/cuda/soft_rasterize_cuda_kernel.cu#L81

Where this thing came from? What are you calculating exactly with `a0`and `t0`

Thanks (:

**Comment by ShichenLiu** [comment]
This is just an intermediate variable to enable more computation sharing. The distance from the triangle to a point is |P - TB|, where P is the point coordinates and T is something like (alpha, 1-alpha, 0) that is a point on the edge of the triangle that is closest to the point, and B is the inverse of the triangle matrix. If we convert P into barycentric coordinates, i.e. P = WB, then we have |(W-T)B|. And this is where these intermediate variables are being used.
