### ISSUE TITLE
Fix pytorch1.5 compile error

### ISSUE THREAD

**Issue by BaldrLector** [ShichenLiu/SoftRas#56]
Hi @ShichenLiu , 

c++ code inside ops will not built since AT_CHECK is deprecated and will thourgh not defined error.
Recommended replace AT_CHECK with TORCH_CHECK to support torch 1.5

To make SoftRas is compiled for pytorch1.5 successfully, please replace `AT_CHECK` with `TORCH_CHECK` for soft_renderer/cuda/*.cpp.

**Comment by ShichenLiu** [comment]
Thanks for you advice!
