### ISSUE TITLE
Altering with opacity

### ISSUE THREAD

**Issue by alakhag** [ShichenLiu/SoftRas#59]
I want to alter the weights of the aggregation function as a function of probability map D and depth z as given in the paper https://arxiv.org/pdf/2004.04572.pdf equation 8.

How can I implement it?

**Comment by alakhag** [comment]
```
if (func_id_rgb == 1) { // D * Softmax (Z)
            if (check_face_frontside(face) || double_side) {
                const scalar_t zp_norm =  (far - zp) / (far - near);
                scalar_t exp_delta_zp = 1.;
                if (zp_norm > softmax_max) {
                    exp_delta_zp = exp( (softmax_max - zp_norm) / gamma_val);
                    softmax_max = zp_norm;
                }
                const scalar_t exp_z = exp( (zp_norm - softmax_max) / gamma_val);
                softmax_sum = exp_delta_zp * softmax_sum + exp_z * soft_fragment;
                for (int k = 0; k < 3; k++) {
                    const scalar_t color_k = forward_sample_texture(texture, w_clip, texture_res, k, texture_sample_type);
                    soft_color[k] = exp_delta_zp * soft_color[k] + exp_z * soft_fragment * color_k;// * soft_fragment;
                }
            }
        }
```
In soft_rasterize_cuda_kernel.cu I see that the weight is calculated here. How does this relate to equation 3 in the paper? https://arxiv.org/pdf/1904.01786.pdf

**Comment by ShichenLiu** [comment]
Hi,

This is the memory-efficient implementation of a softmax function. Usually, softmax is computed by two O(N) functions: 1) find x_j = max_i(x_i), compute s = sum_i(exp(x_i-x_j)); 2) compute y_i = exp(x_i - x_j)/s. Here, x_j is to avoid float point precision problem. 
Here we only want a weighted sum of softmax, say, S = sum_i(w_i * y_i). Also, we can not afford an O(N) memory consumption in limited CUDA RAM. So the alternative way is to compute S on-the-fly. Where for each step j, we keep X_j = max_i(x_i for i in range(j)) and S_j dynamically. This implementation could both accurately avoid float point precision problems and use O(1) memory costs.
