### ISSUE TITLE
 Cannot  converge with only RGB information

### ISSUE THREAD

**Issue by pyni** [ShichenLiu/SoftRas#60]
Hi~
i have tried to do pose optimization with your code.
i find a strange case that, if i use the mask of the rendered image (images[0][3, :,:]), it converges successfully.
But if i use RGB information of rendered image (images[0][0:3, :,:]), it fails.
I wonder whether the code can do back propagation with only RGB data of rendered image?

**Comment by ShichenLiu** [comment]
Hi there,

Backprop through RGB indeed might not as effective as the masks.

**Comment by pyni** [comment]
I see.
Thanks for quickly reply!
