### ISSUE TITLE
Please specify parameter 'dim' when calling torch.cross

### ISSUE THREAD

**Issue by thuliu-yt16** [ShichenLiu/SoftRas#62]
I failed to render meshes using SoftRenderer with `batch_size=3`. Finally, I found that it is because torch.cross is not called with the specific `dim` parameter. 

For example, in `soft_renderer/functional/look_at.py`, line 49-50
if `batch_size=3`, then both `up.shape` and `z_axis.shape` will be `(3, 3)`. 
According to torch documentation, 
<img width="711" alt="截屏2020-10-16 下午10 06 11" src="https://user-images.githubusercontent.com/27289204/96268574-d0d8a900-0ffb-11eb-93f1-9ccdadaf0b22.png">
the `dim` is not given and it will find the dimension 0 with the size 3 and apply cross product column by column, rather than row by row. To fix the bug, please specify `dim=1`. 

I will not create a pull request since I think I cannot find everywhere the problem occurs. Hope you fix the bug.

**Comment by ShichenLiu** [comment]
Hi,

Thanks for bringing this up. I will try to update the code shortly.

**Comment by ShichenLiu** [comment]
Fixed!
