### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by juicyzhucx** [ShichenLiu/SoftRas#68]
when I run python setup.py install,it tells me:
soft_renderer/cuda/load_textures_cuda.cpp(24): error C3861: “AT_CHECK”: 找不到标识符
soft_renderer/cuda/load_textures_cuda.cpp(25): error C3861: “AT_CHECK”: 找不到标识符
soft_renderer/cuda/load_textures_cuda.cpp(26): error C3861: “AT_CHECK”: 找不到标识符
soft_renderer/cuda/load_textures_cuda.cpp(27): error C3861: “AT_CHECK”: 找不到标识符
error: command 'D:\\Microsoft Visual Studio\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

can you tell me how to deal with this? thank you a lot!
my code is built on Python3.7 and PyTorch 1.7.1. CUDA on windows

**Comment by thuliu-yt16** [comment]
replace `AT_CHECK` with `TORCH_CHECK` (#54)

**Comment by ShichenLiu** [comment]
Fixed
