### ISSUE TITLE
misaligned address in windows 10

### ISSUE THREAD

**Issue by tgarsiel** [ShichenLiu/SoftRas#7]
demo_render.py works fine
but in demo_deform.py I get this error (windows 10 python 3.7 cuda 10)
set CUDA_VISIBLE_DEVICES=0 & python examples/demo_deform.py
Loss: 0.8354:   0%|                                                                                              | 0/20000 [00:00<?, ?it/s]THCudaCheck FAIL file=C:/w/1/s/windows/pytorch/aten/src\THC/THCReduceAll.cuh line=327 error=74 : misaligned address
Traceback (most recent call last):
  File "examples/demo_deform.py", line 111, in <module>
    main()
  File "examples/demo_deform.py", line 100, in main
    loss.backward()
  File "D:\apps\python3\lib\site-packages\torch\tensor.py", line 107, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "D:\apps\python3\lib\site-packages\torch\autograd\__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: cuda runtime error (74) : misaligned address at C:/w/1/s/windows/pytorch/aten/src\THC/THCReduceAll.cuh:327

**Comment by ShichenLiu** [comment]
I have not tried it on windows. My environment is on Ubuntu 16/18. It seems that some CUDA code doesn't work on windows. Can you try it on Ubuntu? I will try to figure out where the problem is.

**Comment by tgarsiel** [comment]
Works on Ubuntu.
Thanks.
