### ISSUE TITLE
Qualitative Results

### ISSUE THREAD

**Issue by chicleee** [ShichenLiu/SoftRas#75]
Hi, thanks for your sharing.

I successfully trained and tested the model 250000 iter follow the usages, but the results of single-view mesh reconstruction is lower than the best socre（full: 64.64） mentioned in the paper. It is "Mean IoU: 61.838 for all classes".

Did I miss any details or Did I need to adjust some parameters？

Thanks！

**Comment by ShichenLiu** [comment]
The 64.6 results is trained with our own rendered shading images. You should be able to obtain mIoU over 62 with the provided data.
