### ISSUE TITLE
Question for flatten loss

### ISSUE THREAD

**Issue by YanhaoZhang** [ShichenLiu/SoftRas#83]
Thanks a lot for releasing the code. May I know the formulation of the flatten loss? I did not find it in your paper. Thanks a lot.

**Comment by ShichenLiu** [comment]
Hi, flatten loss is defined as the angle between each pair of triangles in the mesh. Specifically, for each edge `i`, let `theta_i ` be the angle between its two associate triangles, the flatten loss is: `sum_i (cos(theta_i) + 1)^2`. By minimizing the flatten loss, the mesh are forced to be as "flatten" as possible.

**Comment by YanhaoZhang** [comment]
Thanks a lot for your prompt reply. :+1:
